
CREATE TABLE TB_HASHTAG (
    HASHTAG_SEQ NUMERIC(20)  NOT NULL
    ,HASHTAG VARCHAR(300)  NULL
);

CREATE TABLE TB_TRAIL (
    TRAIL_NAME VARCHAR(100)  NULL
    ,TRAIL_CODE VARCHAR(50)  NULL
    ,TRAIL_COORDINATE VARCHAR(300)  NULL
    ,USE_YN VARCHAR(1)  NULL
);

CREATE TABLE TB_INTEREST (
    INTEREST_SEQ NUMERIC(20)  NOT NULL
    ,MIN_COST NUMERIC(20)  NULL
    ,MAX_COST NUMERIC(20)  NULL
    ,TRADE_SE VARCHAR(2)  NULL
    ,IN_ID VARCHAR(50)  NULL
    ,IN_DT DATE  NULL
    ,UP_ID VARCHAR(50)  NULL
    ,UP_DT DATE  NULL
);

CREATE TABLE TB_NOTICE (
    NOTICE_SEQ NUMERIC(20)  NOT NULL
    ,PRODUCT_SEQ NUMERIC(20)  NOT NULL
    ,BUYER_ID VARCHAR(50)  NULL
    ,IN_ID VARCHAR(50)  NULL
    ,IN_DT DATE  NULL
);

CREATE TABLE TB_IF_HASHTAG_PRODUCT (
    HASHTAG_SEQ NUMERIC(20)  NOT NULL
    ,PRODUCT_SEQ NUMERIC(20)  NOT NULL
);

CREATE TABLE TB_IF_HASHTAG_INTEREST (
    HASHTAG_SEQ NUMERIC(20)  NOT NULL
    ,INTEREST_SEQ NUMERIC(20)  NOT NULL
);

CREATE TABLE TB_PRODUCT (
    PRODUCT_SEQ NUMERIC(20)  NOT NULL
    ,TITLE VARCHAR(500)  NULL
    ,MIN_COST NUMERIC(20)  NULL
    ,MAX_COST NUMERIC(20)  NULL
    ,TRADE_SE VARCHAR(2)  NULL
    ,SALE_LOC VARCHAR(300)  NULL
    ,SALE_COORDINATE VARCHAR(300)  NULL
    ,DELEGATE_FILE_ID VARCHAR(50)  NULL
    ,FILE_ID VARCHAR(50)  NULL
    ,CONTENT LONGTEXT  NULL
    ,SALE_SE VARCHAR(2)  NULL
    ,IN_ID VARCHAR(50)  NULL
    ,IN_DT DATE  NULL
    ,UP_ID VARCHAR(50)  NULL
    ,UP_DT DATE  NULL
    ,SALE_START_DATE DATE  NULL
    ,SALE_END_DATE DATE  NULL
    ,READ_CNT NUMERIC(20)  NULL
    ,INTEREST_CNT NUMERIC(20)  NULL
    ,LAST_BUYER_ID VARCHAR(50)  NULL
);
